server:
  port: 8080

spring:
  application:
    name: proxy



  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "http://pixal-gamers-store.s3-website-us-east-1.amazonaws.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        # ==== Swagger per microservicio (acceso centralizado) ====
        # Usuario: http://localhost:8080/usuario/doc/swagger-ui.html
        - id: usuario-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/usuario/doc/**, /usuario/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Producto: http://localhost:8080/producto/doc/swagger-ui.html
        - id: producto-swagger
          uri: http://localhost:8082
          predicates:
            - Path=/producto/doc/**, /producto/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Venta: http://localhost:8080/venta/doc/swagger-ui.html
        - id: venta-swagger
          uri: http://localhost:8083
          predicates:
            - Path=/venta/doc/**, /venta/v3/api-docs/**
          filters:
            - StripPrefix=1

            
        - id: usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/usuarios/**, /api/admin/usuarios/**, /api/servicio/**

        - id: contacto
          uri: http://localhost:8081
          predicates:
            - Path=/api/contacto/**

        - id: productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**

        - id: ventas
          uri: http://localhost:8083
          predicates:
            - Path=/api/ventas/**

     

